basic_config = {
    "core": {
        "map_name": "arena",
        "random_seed": 42,
        "max_steps": 1000,
        "agents_per_team": 1,
        "vision_range": 5.0,
    },
    "extensions": {
        "minion_wave": True,
        "tower": True,
        "jungle": True,
        "wards": False,
        "leveling": False,
        "skills": False,
        "mode_2v2": False,
    },
}


training_config = {
    "SEED": 42,
    "NUM_ACTIONS": 13,
    "USE_BELIEF_INPUT": False,
    "TIMESTEP_PER_BATCH": 1024,
    "MAX_STEPS_PER_EPISODE": 1000,
    "TOTAL_TIMESTEPS": 10_240,
    "LEARNING_AGENT_ID": 0,
    "LR": 3e-4,
    "GAMMA": 0.99,
    "GAE_LAMBDA": 0.95,
    "CLIP_EPS": 0.2,
    "VF_COEF": 0.5,
    "ENT_COEF": 0.01,
    "MAX_GRAD_NORM": 0.5,
    "UPDATE_EPOCHS": 4,
    "NUM_MINIBATCHES": 4,
    "HIDDEN_DIM": 64,
    "ACTIVATION": "tanh",
    "NPC_POLICY_ID_SOURCE": "index",
    "opponent_strategy": "aggressive",
    "strategy_switch_mode": "time_based",
    "DEFAULT_NPC_POLICY": "neutral",
    "NPC_POLICIES": {
        1: "aggressive",
    },
    "RANDOMIZE_NPC_POLICY_EACH_EPISODE": True,
    "NPC_POLICY_IDS": [1],
    "NPC_STRATEGY_POOL": [
        "aggressive",
        "farming",
        "neutral",
        "observation_craving",
    ],
    "NPC_SWITCH_STEP_RANGE": [150, 850],
}
